spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017
      database: transaction
#      host: localhost
#      port: 27017
#      username: admin
#      password: admin
#      database: transaction

management:
  endpoints:
    web:
      exposure:
        include: health, beans

transaction:
  validation:
    enabled: false
    banco: true
    horario: true

server:
  port: 8082